-module(main).
-export([start/4]).

%% generated by chatgpt after asking it to convert the go version 
%% I then cleaned up the cli args

-record(chan, {
    cap,
    size = 0,
    buf,
    sendq,
    recvq
}).

start(Sup, N, M, K) ->
    Y = find_all(Sup, N, M, K),
    io:format("[main] received: ~p~n", [Y]).

heartbeat(Sup) -> 
    %% Send heartbeat so supervisor knows we are still alive
    Sup ! {heartbeat, self()}.

find_all(Sup, N, M, K) ->
    heartbeat(Sup),
    Found = chan_new(N),
    Limit = chan_new(M),
    produce(Sup, Found, Limit, K),
    collect(Sup, K, Found, []).

produce(_Sup, _Found, _Limit, 0) -> 
    io:format("[main] finished producing~n");
produce(Sup, Found, Limit, K) -> 
    io:format("[main] producing (~p)~n", [K]),
    chan_send(Sup, Limit, token),
    spawn(fun() ->
        P = K,
        chan_send(Sup, Found, P),
        _ = chan_recv(Sup, Limit),
        ok
    end),
    produce(Sup, Found, Limit, K - 1).

collect(_Sup, 0, _Found, Acc) ->
    lists:reverse(Acc);
collect(Sup, N, Found, Acc) ->
    P = chan_recv(Sup, Found),
    collect(Sup, N - 1, Found, [P | Acc]).

chan_new(Cap) when is_integer(Cap), Cap >= 0 ->
    spawn(fun() ->
        chan_loop(#chan{
            cap = Cap,
            buf = queue:new(),
            sendq = queue:new(),
            recvq = queue:new()
        })
    end).

chan_send(Sup, Pid, Msg) ->
    Ref = make_ref(),
    Pid ! {send, self(), Ref, Msg},
    receive
        {Ref, ok} -> heartbeat(Sup), ok
    end.

chan_recv(Sup, Pid) ->
    Ref = make_ref(),
    Pid ! {recv, self(), Ref},
    receive
        {Ref, Msg} -> heartbeat(Sup), Msg
    end.

chan_loop(State0) ->
    State1 = drain(State0),
    receive
        {send, From, Ref, Msg} ->
            chan_loop(enqueue_send(State1, From, Ref, Msg));
        {recv, From, Ref} ->
            chan_loop(enqueue_recv(State1, From, Ref));
        stop ->
            ok
    end.

enqueue_send(State = #chan{sendq = Q}, From, Ref, Msg) ->
    State#chan{sendq = queue:in({From, Ref, Msg}, Q)}.

enqueue_recv(State = #chan{recvq = Q}, From, Ref) ->
    State#chan{recvq = queue:in({From, Ref}, Q)}.

drain(State) ->
    case step(State) of
        none ->
            State;
        State1 ->
            drain(State1)
    end.

step(State = #chan{buf = Buf, sendq = SendQ, recvq = RecvQ, size = Size, cap = _}) ->
    case queue:out(RecvQ) of
        {{value, {RecvPid, RecvRef}}, RecvQ1} ->
            case queue:out(Buf) of
                {{value, Msg}, Buf1} ->
                    RecvPid ! {RecvRef, Msg},
                    State#chan{buf = Buf1, recvq = RecvQ1, size = Size - 1};
                {empty, _} ->
                    case queue:out(SendQ) of
                        {{value, {SendPid, SendRef, Msg}}, SendQ1} ->
                            SendPid ! {SendRef, ok},
                            RecvPid ! {RecvRef, Msg},
                            State#chan{sendq = SendQ1, recvq = RecvQ1};
                        {empty, _} ->
                            none
                    end
            end;
        {empty, _} ->
            maybe_buffer_send(State)
    end.

maybe_buffer_send(State = #chan{buf = Buf, sendq = SendQ, recvq = RecvQ, size = Size, cap = Cap}) ->
    case {queue:is_empty(RecvQ), queue:out(SendQ)} of
        {true, {{value, {SendPid, SendRef, Msg}}, SendQ1}} when Size < Cap ->
            SendPid ! {SendRef, ok},
            State#chan{buf = queue:in(Msg, Buf), sendq = SendQ1, size = Size + 1};
        _ ->
            none
    end.
