-module(sup).
-export([run/1, start/3]).

%% adapted from code generated by claude

%% multiplier for number of milliseconds we should provide per K
-define(K_MULTI, 10).

%% ---------------------------------------------------------------------------
%% Public API
%% ---------------------------------------------------------------------------

%% Entry point called by run.erl after it has parsed the CLI args.
start(N, M, K) ->
    process_flag(trap_exit, true),
    io:format("[sup] starting main with:~nn := ~p~nm := ~p~nk := ~p~n", [N, M, K]),
    io:format("[sup] (~p + ~p >= ~p) looks ~s~n", [N, M, K, safestr ((N + M) >= K)]),
    MainPid = spawn_link(main, start, [self(), N, M, K]),
    loop(MainPid, K * ?K_MULTI).

%% ---------------------------------------------------------------------------
%% Internal
%% ---------------------------------------------------------------------------

safestr(true) -> "safe";
safestr(false) -> "unsafe".

loop(MainPid, Timeout) ->
    receive
        %% main is alive – reset the timer and keep waiting
        {heartbeat, MainPid} ->
            % io:format("[sup] heartbeat received from main~n"),
            loop(MainPid, Timeout);

        %% main exited normally (exit reason 'normal' arrives via trap_exit)
        {'EXIT', MainPid, normal} ->
            io:format("[sup] main finished successfully~n"),
            halt(0);

        %% main exited with an error
        {'EXIT', MainPid, Reason} ->
            io:format("[sup] main exited with error: ~p~n", [Reason]),
            halt(1)

    after Timeout ->
        %% No heartbeat received within the window – main is stuck
        io:format("[sup] no heartbeat received within ~pms – main is stuck, killing it~n",
                  [Timeout]),
        exit(MainPid, kill),
        halt(1)
    end.

%% Fallback: called directly by erl -s sup run a …
%% Delegates to run.erl for proper arg parsing.
run(Args) ->
    run:start(Args).
