-module(test).
-export([main/1, find_all/3]).

% generated by chatgpt after asking it to convert the go version 

-record(chan, {
    cap,
    size = 0,
    buf,
    sendq,
    recvq
}).

main(Args) ->
    {N, M, K} = get_args(Args),
    io:format("spawning FindAll with:~nn := ~p~nm := ~p~nk := ~p~n", [N, M, K]),
    Y = find_all(N, M, K),
    io:format("received: ~p~n", [Y]),
    ok.

find_all(N, M, K) ->
    Found = chan_new(N),
    Limit = chan_new(M),

    lists:foreach(
      fun(I) ->
          chan_send(Limit, token),
          spawn(fun() ->
              P = I,
              chan_send(Found, P),
              _ = chan_recv(Limit),
              ok
          end)
      end,
      lists:seq(0, K - 1)
    ),

    collect(K, Found, []).

collect(0, _Found, Acc) ->
    lists:reverse(Acc);
collect(N, Found, Acc) ->
    P = chan_recv(Found),
    collect(N - 1, Found, [P | Acc]).

get_args(["safe"]) ->
    {5, 6, 3};
get_args(["unsafe"]) ->
    {1, 10, 12};
get_args([A, B, C]) ->
    {get_int(A), get_int(B), get_int(C)};
get_args(_) ->
    error("Unrecognised input. Either use one of the presets \"safe\" or \"unsafe\", or input 3 integers for n, m, k. A \"safe\" input is one where: n + m >= k").

get_int(S) ->
    list_to_integer(S).

chan_new(Cap) when is_integer(Cap), Cap >= 0 ->
    spawn(fun() ->
        chan_loop(#chan{
            cap = Cap,
            buf = queue:new(),
            sendq = queue:new(),
            recvq = queue:new()
        })
    end).

chan_send(Pid, Msg) ->
    Ref = make_ref(),
    Pid ! {send, self(), Ref, Msg},
    receive
        {Ref, ok} -> ok
    end.

chan_recv(Pid) ->
    Ref = make_ref(),
    Pid ! {recv, self(), Ref},
    receive
        {Ref, Msg} -> Msg
    end.

chan_loop(State0) ->
    State1 = drain(State0),
    receive
        {send, From, Ref, Msg} ->
            chan_loop(enqueue_send(State1, From, Ref, Msg));
        {recv, From, Ref} ->
            chan_loop(enqueue_recv(State1, From, Ref));
        stop ->
            ok
    end.

enqueue_send(State = #chan{sendq = Q}, From, Ref, Msg) ->
    State#chan{sendq = queue:in({From, Ref, Msg}, Q)}.

enqueue_recv(State = #chan{recvq = Q}, From, Ref) ->
    State#chan{recvq = queue:in({From, Ref}, Q)}.

drain(State) ->
    case step(State) of
        none ->
            State;
        State1 ->
            drain(State1)
    end.

step(State = #chan{buf = Buf, sendq = SendQ, recvq = RecvQ, size = Size, cap = _}) ->
    case queue:out(RecvQ) of
        {{value, {RecvPid, RecvRef}}, RecvQ1} ->
            case queue:out(Buf) of
                {{value, Msg}, Buf1} ->
                    RecvPid ! {RecvRef, Msg},
                    State#chan{buf = Buf1, recvq = RecvQ1, size = Size - 1};
                {empty, _} ->
                    case queue:out(SendQ) of
                        {{value, {SendPid, SendRef, Msg}}, SendQ1} ->
                            SendPid ! {SendRef, ok},
                            RecvPid ! {RecvRef, Msg},
                            State#chan{sendq = SendQ1, recvq = RecvQ1};
                        {empty, _} ->
                            none
                    end
            end;
        {empty, _} ->
            maybe_buffer_send(State)
    end.

maybe_buffer_send(State = #chan{buf = Buf, sendq = SendQ, recvq = RecvQ, size = Size, cap = Cap}) ->
    case {queue:is_empty(RecvQ), queue:out(SendQ)} of
        {true, {{value, {SendPid, SendRef, Msg}}, SendQ1}} when Size < Cap ->
            SendPid ! {SendRef, ok},
            State#chan{buf = queue:in(Msg, Buf), sendq = SendQ1, size = Size + 1};
        _ ->
            none
    end.
